apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  labels: { app: flask-app }
spec:
  replicas: 1
  selector:
    matchLabels: { app: flask-app }
  template:
    metadata:
      labels: { app: flask-app }
    spec:
      containers:
        - name: flask-app
          image: 2024tm93086/flask-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
